name: mokura
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  get_storage: ^2.1.1
  dio: ^5.4.1
  geolocator: ^12.0.0
  flutter_barcode_scanner: ^2.0.0
  qr_code_dart_scan: ^0.8.0
  qr_code_scanner: ^1.0.1
  webview_flutter: ^4.7.0
  google_fonts: ^6.2.1
  flutter_bluetooth_serial_ble: ^0.5.0
  image_picker: ^1.1.1
  intl: 0.19.0
  firebase_core: 3.2.0
  firebase_messaging: 15.0.3
  flutter_local_notifications: 17.2.1+2
  flutter_image_compress: 2.3.0
  flutter: 
    sdk: flutter
  syncfusion_flutter_gauges: 25.1.35
  animated_battery_gauge: ^0.2.0
  web_socket_channel: ^3.0.1
  url_launcher: ^6.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/avatar.png
  uses-material-design: true

